name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install lua
      run: brew install lua
    - name: Build
      run: swift build
  test-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install lua
      run: brew install lua
    - name: Run tests
      run: swift test
      
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install conan
      run: sudo pip install conan
    - name: Install lua
      run: conan install .
    - name: Build
      run: swift build
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install conan
      run: pip install conan
    - name: Install lua
      run: conan install .
    - name: Run tests
      run: swift test
