name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install lua
      run: brew install lua
    - name: Build
      run: swift build
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install lua
      run: brew install lua
    - name: Run tests
      run: swift test
